---
name: pedantic_sensuikan1973
version: 5.10.0
description: The best Dart analyzer settings are used. sensuikan1973 edition.
homepage: https://github.com/sensuikan1973/pedantic_sensuikan1973

environment:
  sdk: '>=3.7.0 <4.0.0'
dependencies:
  flutter_lints: ^5.0.0
